# The Site Configuration
# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: Australia/Sydney

# jekyll-seo-tag settings
title: Simply Software Development
tagline: >-
  Notes and examples of a developer experiences of
  wrestling with the beasts and dragons as nothing
  has changed and yet everything is different.
description: >-
  Notes and examples of a developer experiences of
  wrestling with the beasts and dragons as nothing
  has changed and yet everything is different.

# Fill in the protocol & hostname for your site.
url: "https://bengthedberg.github.io"
baseurl: ""

github:
  username: bengthedberg

twitter:
  username: TheHedberg

social:
  name: Bengt Hedberg
  email: bengt.hedberg@gmail.com
  links:
    - https://twitter.com/TheHedberg
    - https://github.com/bengthedberg
    - https://www.linkedin.com/in/bengthedberg

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID

# Prefer color scheme setting.
# Options:
#   light - Use the light color scheme
#   dark  - Use the dark color scheme
theme_mode: # [light | dark]

# The CDN endpoint for media resources.
# Notice that once it is assigned, the CDN url
# will be added to all media resources (site avatar, post images, etc.)
cdn:

# the avatar on sidebar, support local or CORS resources
avatar: https://github.com/bengthedberg.png

# The URL of the site-wide social preview image used in SEO `og:image` meta tag.
social_preview_image: # string, local or CORS resources

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname.
  # utterances settings
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    strict: # optional, default to '0'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    env: # [development | production]

pwa:
  enabled: true

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _tabs
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
